CREATE DATABASE usermap;

CREATE TABLE usermap.usermap (id INT AUTO_INCREMENT PRIMARY KEY, users TEXT, ip VARCHAR(64), mac VARCHAR(64) UNIQUE, compname VARCHAR(64), updated TIMESTAMP DEFAULT NOW());

CREATE USER monitor IDENTIFIED BY 't0ps3cr3t';
GRANT SELECT, INSERT, UPDATE ON usermap.usermap TO monitor REQUIRE SSL;

FLUSH PRIVILEGES;

